# Generated by Django 4.1.7 on 2023-03-07 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('dns_txt', models.CharField(blank=True, max_length=50, unique=True)),
                ('last_ownership_check', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=2048)),
                ('note', models.CharField(blank=True, max_length=2048)),
                ('short_url', models.URLField(error_messages={'unique': '단축 URL이 이미 존재합니다. Domain과 alias를 확인하십시오.'}, max_length=128, unique=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorty.domain')),
            ],
        ),
    ]
