# Generated by Django 4.1.7 on 2023-03-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='last_ownership_check',
            field=models.DateTimeField(null=True),
        ),
    ]
