# Generated by Django 4.1.7 on 2023-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surl',
            name='short_url',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='surl',
            name='alias',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
