# Generated by Django 4.1.7 on 2023-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0002_surl_short_url_alter_surl_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surl',
            name='alias',
            field=models.CharField(max_length=128),
        ),
    ]
