# Generated by Django 4.1.7 on 2023-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0002_alter_domain_last_ownership_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dns_txt',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
