# Generated by Django 4.1.7 on 2023-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_alter_domain_dns_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dns_txt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
