# Generated by Django 4.1.7 on 2023-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0004_alter_domain_dns_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dns_txt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='last_ownership_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
