# Generated by Django 4.1.7 on 2023-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0004_remove_surl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='surl',
            name='short_url',
            field=models.URLField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
