# Generated by Django 4.1.7 on 2023-07-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0005_alter_domain_dns_txt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='host_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
