# Generated by Django 4.1.7 on 2023-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0005_surl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surl',
            name='short_url',
            field=models.URLField(max_length=128, unique=True),
        ),
    ]
