# Generated by Django 4.1.10 on 2026-04-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0006_domain_host_allowed'),
        ('shorty', '0006_domain_host_allowed_surl_visit_counts'),
    ]

    operations = [
    ]
