# Generated by Django 4.1.7 on 2023-03-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0006_alter_surl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
