# Generated by Django 4.1.10 on 2026-04-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0007_merge_20260401_1449'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surl',
            index=models.Index(fields=['domain', 'alias'], name='shorty_surl_domain_alias_idx'),
        ),
        migrations.AddConstraint(
            model_name='surl',
            constraint=models.UniqueConstraint(fields=('domain', 'alias'), name='shorty_unique_alias_per_domain'),
        ),
    ]
