# Generated by Django 4.2.29 on 2026-04-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0008_surl_shorty_surl_domain_alias_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('surl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='shorty.surl')),
            ],
            options={
                'indexes': [models.Index(fields=['surl', 'created_at'], name='shorty_click_surl_created_idx')],
            },
        ),
    ]
