# Generated by Django 4.2.29 on 2026-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0009_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='browser',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='referrer',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='surl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
