# Generated by Django 4.2.29 on 2026-04-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0010_clickevent_browser_clickevent_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expired_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_expired_fallbacks', to='shorty.surl'),
        ),
        migrations.AddField(
            model_name='domain',
            name='expired_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='inactive_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_inactive_fallbacks', to='shorty.surl'),
        ),
        migrations.AddField(
            model_name='domain',
            name='inactive_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='missing_alias_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_missing_alias_fallbacks', to='shorty.surl'),
        ),
        migrations.AddField(
            model_name='domain',
            name='missing_alias_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='root_action',
            field=models.CharField(choices=[('dashboard', 'Open Shorty dashboard'), ('redirect_url', 'Redirect to custom URL'), ('redirect_link', 'Redirect to registered short link'), ('show_message', 'Show message page')], default='dashboard', max_length=32),
        ),
        migrations.AddField(
            model_name='domain',
            name='root_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='root_redirect_surl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_root_redirects', to='shorty.surl'),
        ),
        migrations.AddField(
            model_name='domain',
            name='root_redirect_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
