# Generated by Django 4.2.29 on 2026-04-07 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorty', '0011_domain_expired_fallback_domain_expired_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='root_redirect_surl',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='root_redirect_url',
        ),
        migrations.AlterField(
            model_name='domain',
            name='root_action',
            field=models.CharField(choices=[('dashboard', 'Open Shorty dashboard'), ('fallback', 'Redirect to registered fallback URL'), ('show_message', 'Show message page')], default='dashboard', max_length=32),
        ),
        migrations.CreateModel(
            name='FallbackDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=2048)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='root_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_root_fallbacks', to='shorty.fallbackdestination'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='expired_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_expired_fallbacks', to='shorty.fallbackdestination'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='inactive_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_inactive_fallbacks', to='shorty.fallbackdestination'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='missing_alias_fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_missing_alias_fallbacks', to='shorty.fallbackdestination'),
        ),
        migrations.AddConstraint(
            model_name='fallbackdestination',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='shorty_unique_fallback_name_per_owner'),
        ),
    ]
