# Generated by Django 4.2.29 on 2026-04-07 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorty', '0012_remove_domain_root_redirect_surl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expired_action',
            field=models.CharField(choices=[('inherit', 'Use global default'), ('fallback', 'Redirect to fallback URL'), ('message', 'Show message')], default='inherit', max_length=32),
        ),
        migrations.AddField(
            model_name='domain',
            name='inactive_action',
            field=models.CharField(choices=[('inherit', 'Use global default'), ('fallback', 'Redirect to fallback URL'), ('message', 'Show message')], default='inherit', max_length=32),
        ),
        migrations.AddField(
            model_name='domain',
            name='missing_alias_action',
            field=models.CharField(choices=[('inherit', 'Use global default'), ('fallback', 'Redirect to fallback URL'), ('message', 'Show message')], default='inherit', max_length=32),
        ),
        migrations.AlterField(
            model_name='domain',
            name='root_action',
            field=models.CharField(choices=[('inherit', 'Use global default'), ('dashboard', 'Open Shorty dashboard'), ('fallback', 'Redirect to registered fallback URL'), ('show_message', 'Show message page')], default='inherit', max_length=32),
        ),
        migrations.CreateModel(
            name='GlobalRoutingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_action', models.CharField(choices=[('dashboard', 'Open Shorty dashboard'), ('fallback', 'Redirect to fallback URL'), ('show_message', 'Show message')], default='dashboard', max_length=32)),
                ('root_message', models.CharField(blank=True, max_length=255)),
                ('missing_alias_action', models.CharField(choices=[('fallback', 'Redirect to fallback URL'), ('message', 'Show message')], default='message', max_length=32)),
                ('missing_alias_message', models.CharField(blank=True, max_length=255)),
                ('inactive_action', models.CharField(choices=[('fallback', 'Redirect to fallback URL'), ('message', 'Show message')], default='message', max_length=32)),
                ('inactive_message', models.CharField(blank=True, max_length=255)),
                ('expired_action', models.CharField(choices=[('fallback', 'Redirect to fallback URL'), ('message', 'Show message')], default='message', max_length=32)),
                ('expired_message', models.CharField(blank=True, max_length=255)),
                ('expired_fallback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_expired_fallbacks', to='shorty.fallbackdestination')),
                ('inactive_fallback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_inactive_fallbacks', to='shorty.fallbackdestination')),
                ('missing_alias_fallback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_missing_alias_fallbacks', to='shorty.fallbackdestination')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_routing_settings', to=settings.AUTH_USER_MODEL)),
                ('root_fallback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_root_fallbacks', to='shorty.fallbackdestination')),
            ],
        ),
    ]
