# Generated by Django 4.2.29 on 2026-04-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0013_domain_expired_action_domain_inactive_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fallbackdestination',
            name='is_active',
        ),
    ]
