# Generated by Django 4.2.29 on 2026-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0014_remove_fallbackdestination_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surl',
            name='short_url',
            field=models.URLField(error_messages={'unique': 'That short URL already exists. Check the domain and alias.'}, max_length=128, unique=True),
        ),
    ]
