# Generated by Django 4.2.29 on 2026-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0015_alter_surl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='surl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]
